[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
atomic = true
known_first_party = ["app"]
skip = ["migrations"]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
    "migrations",
    "get-pip.py",
]
fix = true

[tool.mypy]
python_version = "3.11"
strict = false
explicit_package_bases = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true
exclude = ["migrations", "get-pip.py", "app/routers", "app/keyboards", "tests"]
files = [
    "app/db",
    "app/services",
    "app/config.py",
    "app/main.py",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
